import './globals.scss'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Header from './components/layout/header/Header'
import MainProvider from './providers/MainProvider'
import SectionNav from './components/profile/section-navigate/SectionNav'
const myFont = localFont({
	src: [
		{
			path: './fonts/MuseoSansCyrl300.woff',
			weight: '300',
			style: 'normal'
		},
		{
			path: './fonts/MuseoSansCyrl500.woff',
			weight: '500',
			style: 'italic'
		},
		{
			path: './fonts/MuseoSansCyrl700.woff',
			weight: '700',
			style: 'normal'
		}
	]
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<head>
				<link rel='preconnect' href='https://fonts.googleapis.com' />
				<link
					rel='preconnect'
					href='https://fonts.gstatic.com'
					crossOrigin=''
				/>
				<link
					href='https://fonts.googleapis.com/css2?family=Mulish:wght@400;500;600;700;800;900&display=swap'
					rel='stylesheet'
				/>
			</head>
			<body className={myFont.className}>
				<MainProvider>
					<div className='min-h-screen flex flex-col'>
						<Header />
						<main className='main'>{children}</main>
					</div>
				</MainProvider>
			</body>
		</html>
	)
}
//"react-redux-toastr": "^7.6.11",
